### ISSUE TITLE
IndexError computing sparse kernels with different atomic species sets

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#268]
This error comes from trying to adapt the `MLIP_example` notebook to a prediction on a sample with different sets of atomic species -- in this case, 50 structures randomly selected from QM7b. Minimal working example attached. This error happens on the serialization branch (`feat/split_pr_test_1`) but I'm guessing it'll be present in `master` as well. I haven't tested it in `feat/sparsified_soap` yet, so maybe it'll be fixed there.

Excerpt from MWE:
```python
scalar_hypers = {
    'soap_type': 'PowerSpectrum',
    'interaction_cutoff': 5.0,
    'cutoff_function_type': 'RadialScaling',
    'cutoff_function_parameters': {
        'rate': 1,
        'scale': 2.327,
        'exponent': 4.417
    },
    'cutoff_smooth_width': 0.5,
    'max_radial': 8,
    'max_angular': 6,
    'gaussian_sigma_constant': 0.375,
    'gaussian_sigma_type': 'Constant',
    'radial_basis': 'GTO',
    'normalize': True,
    'compute_gradients': False,
    'expansion_by_species_method': 'structure wise',
}
scalar_rep = SphericalInvariants(**scalar_hypers)

[...]

n_sparse = {1: 50, 6: 50, 7: 39, 8: 49, 16: 2}
compressor = CURFilter(scalar_rep, n_sparse, act_on='sample per species')
sparse_points_cur = compressor.fit_transform(mols_scalar_soaps)

kernel = Kernel(scalar_rep, name='GAP', zeta=2, target_type='Atom', kernel_type='Sparse')
kernel_sparse = kernel(sparse_points_cur) # Throws error
```
[mwe.zip](https://github.com/cosmo-epfl/librascal/files/4451646/mwe.zip)

Output:
```
% python kernel_error_demo.py fps
{1, 6, 7, 8, 16}
Traceback (most recent call last):
  File "kernel_error_demo.py", line 77, in <module>
    kernel_sparse = kernel(sparse_points) # Throws error
  File "/home/max/Work/librascal/build/rascal/models/kernels.py", line 133, in __call__
    return self._kernel.compute(X)
IndexError: map::at
% python kernel_error_demo.py cur
{1, 6, 7, 8, 16}
Species 1: 416 occurrences
Species 6: 246 occurrences
Species 7: 40 occurrences
Species 8: 50 occurrences
Species 16: 3 occurrences
The number of pseudo points selected by central atom species is: {1: 50, 6: 50, 7: 39, 8: 49, 16: 2}
Selecting species: 1
Reconstruction RMSE=1.462e+00
Selecting species: 6
Reconstruction RMSE=1.887e+00
Selecting species: 7
Reconstruction RMSE=1.704e-02
Selecting species: 8
Reconstruction RMSE=1.074e-05
Selecting species: 16
Reconstruction RMSE=4.143e-02
Traceback (most recent call last):
  File "kernel_error_demo.py", line 95, in <module>
    kernel_sparse = kernel(sparse_points_cur) # Throws error
  File "/home/max/Work/librascal/build/rascal/models/kernels.py", line 133, in __call__
    return self._kernel.compute(X)
IndexError: map::at
```

**Comment by felixmusil** [comment]
I had similar problems. I am not sure what it is due to though. Just increase the number of structures so that you can pick 10 sparse points from each species and it will work. I will investigate this problem when I have the time.

**Comment by max-veit** [comment]
... that's going to take a lot of structures; chlorine and sulphur are very rarely represented in that dataset. Does it work if one of the elements is not at all represented (e.g. no chlorine)?

And what on Earth is special about 10 sparse points? This is a real head-scratcher.

**Comment by felixmusil** [comment]
You can exclude all structures with these species from the dataset and that will do the trick too. 
I am not sure myself and 10 is just a number that seems to work, might work with a bit less too. And I really can't tell on top of my head why this is a problem at all.

**Comment by max-veit** [comment]
It happened again, this time with well over 10 points per species. The structure is BaTiO3, eight formula units per cell.

```python
disps = ase.io.read('source_displacements/82-135.xyz', ':')

soap_hypers = {
    'soap_type': 'PowerSpectrum',
    'interaction_cutoff': 5.5,
    'cutoff_smooth_width': 0.5,
    'cutoff_function_type': 'RadialScaling',
    'cutoff_function_parameters': {
        'rate': 1,
        'scale': 3.5,
        'exponent': 4
    },
    'max_radial': 8,
    'max_angular': 6,
    'gaussian_sigma_type': 'Constant',
    'gaussian_sigma_constant': 0.5,
    'radial_basis': 'GTO',
    'normalize': True,
    'compute_gradients': True
}
rep = SphericalInvariants(**soap_hypers)

[geom.wrap(eps=1E-10) for geom in disps]

soaps = rep.transform(disps)

n_sparse = {8: 500, 22: 250, 56: 250}
compressor = CURFilter(rep, n_sparse, act_on='sample per species')
sparse_points_cur = compressor.fit_transform(soaps)
dump_obj('rascaltest/sparsepoints.json', sparse_points_cur)


kernel = Kernel(rep, name='GAP', zeta=4, target_type='Atom', kernel_type='Sparse')
kernel_sparse = kernel(sparse_points_cur)
```
Output:
```
Selecting species: 8
Reconstruction RMSE=1.179e-01
Selecting species: 22
Reconstruction RMSE=6.938e-02
Selecting species: 56
Reconstruction RMSE=4.605e-02
Traceback (most recent call last):
  File "FerroERascal.py", line 51, in <module>
    kernel_sparse_full = kernel(soaps, sparse_points_cur)
  File "/home/veit/librascal/build/rascal/models/kernels.py", line 147, in __call__
    return self._kernel.compute(self._representation, X, Y)
IndexError: map::at
```
I have yet to successfully build a sparse kernel in librascal; this error is keeping me from using librascal for any production project.

**Comment by felixmusil** [comment]
Can you also attach the structure file ?

**Comment by Luthaf** [comment]
Re-opening to track the [remaining problem](https://github.com/cosmo-epfl/librascal/pull/271#pullrequestreview-398103639)
